openapi: "3.0.0"

info:
  version: 0.0.1
  title: Steady Daemon

paths:
  /steady/application/{name}:
    parameters:
      - name: name
        in: path
        description: tags to filter by
        required: true
        schema:
          type: string
    post:
      operationId: createApplication
      requestBody:
        description: Application to add to daemon
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - script
              properties:
                script:
                  type: string
      responses:
        "201":
          description: "success response"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Application"
        default:
          description: unexpected error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
    delete:
      operationId: deleteApplication
      responses:
        "200":
          description: "application was deleted"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Application"
        default:
          description: unexpected error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
components:
  schemas:
    Application:
      type: object
      required:
        - name
      properties:
        name:
          type: string

    Error:
      type: object
      required:
        - msg
      properties:
        msg:
          type: string
