// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.16.0

package db

import (
	"time"
)

type Application struct {
	ID               int64
	ServiceVersionID int64
	UserID           int64
	Name             string
}

type LoginToken struct {
	UserID    int64
	Token     string
	CreatedAt time.Time
}

type Service struct {
	ID     int64
	Name   string
	UserID int64
}

type ServiceVersion struct {
	ID        int64
	ServiceID int64
	Version   string
	Source    string
}

type User struct {
	ID       int64
	Email    string
	Username string
}
