settings:
  legacy:
    force: false
    interval: 0s
schema:
  - name: dev
    path: .
    commands:
      run:
        status: true
    watcher:
      extensions: ["go", "html", "js", "css"]
      paths:
        - ../../
      ignored_paths:
        - .git
        - .realize
        - vendor
        - ../../web/app/node_modules
        - ../../examples
