name: "Test"
on:
  push:
jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: cachix/install-nix-action@v18
        with:
          nix_path: nixpkgs=channel:nixos-unstable
      - name: download nix deps
        run: nix-shell --run "echo \"Rock steady\""
      - name: download go deps
        run: go mod download
      - name: Confirm there are not untracked changes after generate
        run: |
          make generate
          git status
          [[ -z $(git status -s) ]]
      - env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
        run: |
          make test_ci
      # - name: lint
      #   run: make lint
